Name: "go-base-service"
AppNames: ["HTTP_SERVER", "GRPC_SERVER"]
Server:
    HTTPPort: 8080
    GRPCPort: 8081
Controller:
    Name: "http"
    HTTP:
        Port: 8080
        GinMode: "release"
        ReadTimeoutMillis: 500
        WriteTimeoutMillis: 500
        Ping: {}
Repository:
    Name: "redis"
    Redis: {}
DynamicConfig:
    Logger:
        AppName: go-base-service
        Build: prod
        Level: debug # info/error
    Service:
        Ping: {}
ConfigRepository:
    name: "memory"