// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/gobaserservice/v1/gobaserservice.proto

package gobaseservice_v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_gobaserservice_v1_gobaserservice_proto protoreflect.FileDescriptor

const file_proto_gobaserservice_v1_gobaserservice_proto_rawDesc = "" +
	"\n" +
	",proto/gobaserservice/v1/gobaserservice.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17proto/common/ping.proto2\x93\x01\n" +
	"\vBaseService\x12\x83\x01\n" +
	"\x04Ping\x12\x0f.v1.PingRequest\x1a\x10.v1.PingResponse\"X\x92A6\n" +
	"\x04Ping\x12\x0fPing the server\x1a\x1dCheck if the server is alive.\x82\xd3\xe4\x93\x02\x19\x12\x17/gobaserservice/v1/pingB\x9b\x01\x92A\x83\x01\x12a\n" +
	"\x11GoBaseService API\x12DGoBaseService is a basic service to show how to structure a service.2\x06v1.0.0j\x1e\n" +
	"\x04Ping\x12\x16Health check endpointsZ\x12./gobaseservice_v1b\x06proto3"

var file_proto_gobaserservice_v1_gobaserservice_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: v1.PingRequest
	(*PingResponse)(nil), // 1: v1.PingResponse
}
var file_proto_gobaserservice_v1_gobaserservice_proto_depIdxs = []int32{
	0, // 0: v1.BaseService.Ping:input_type -> v1.PingRequest
	1, // 1: v1.BaseService.Ping:output_type -> v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gobaserservice_v1_gobaserservice_proto_init() }
func file_proto_gobaserservice_v1_gobaserservice_proto_init() {
	if File_proto_gobaserservice_v1_gobaserservice_proto != nil {
		return
	}
	file_proto_common_ping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gobaserservice_v1_gobaserservice_proto_rawDesc), len(file_proto_gobaserservice_v1_gobaserservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gobaserservice_v1_gobaserservice_proto_goTypes,
		DependencyIndexes: file_proto_gobaserservice_v1_gobaserservice_proto_depIdxs,
	}.Build()
	File_proto_gobaserservice_v1_gobaserservice_proto = out.File
	file_proto_gobaserservice_v1_gobaserservice_proto_goTypes = nil
	file_proto_gobaserservice_v1_gobaserservice_proto_depIdxs = nil
}
